### ISSUE TITLE
Dependency TabixFile not available

### ISSUE THREAD

**Issue by lima1** [bernatgel/CopyNumberPlots#2]
Hi Bernat, 

I was trying to install your package but looks like TabixFile is not available.

I'm interested in replacing the copy number plots of my PureCN package (https://bioconductor.org/packages/devel/bioc/vignettes/PureCN/inst/doc/PureCN.pdf, Figures 4 and 5) with karotypeR and it's exciting that you are already working on BAF plots etc. Do you think it's possible to generate those existing plots with CopyNumberPlots? Do you plan to release this on Bioconductor? Can I help?

Markus

**Comment by bernatgel** [comment]
Hi Markus,

CopyNumberPlots is still in early development. The basic functionality is already in place and it works well, but there are still some features I'd like to add before submitting to bioconductor (mainly accepting the output from various copy number calling tools as input) and more important, all documentation is still missing. 

This package is not in the top of my todo list, since in its current state it already does what I need from it. If there is interest in it going to Bioconductor sooner than later I can try to allocate some time for it (at least to improve documentation and leave it in good condition to submit it to Bioconductor) and leave the additional features and input formats for the future. 

If you want to replace the code to generate these figures with code using karyoploteR you can either use karyoploteR directly, copy/paste/re-use the code in CopyNumberPlots into your own functions or wait for it to be included in Biconductor. 

If you really want to help with improving the package to the point of submitting it to Bioconductor we can talk about it. I'll be happy to accept some help!

Bernat

**Comment by lima1** [comment]
Great, thank you Bernat for getting back to me! There is no rush, the Bioconductor release next October would nice. I'll have a look at see what's missing for me feature-wise. In the meantime, where can I get TabixFile?

**Comment by bernatgel** [comment]
Hi Markus,

I've updated the package so it now build and checks with no errors on Bioconductor devel. It will also need a recent version of karyoploteR (probabbly the devel one) wich include the autotrack and is.color functions. If you chacke out the code you should be able to build it and install it into your system and this will give you TabixFile from Rsamtools.

Please let me know if you have any problem with it or if think any feature is missing.

Bernat
